### Інсталюємо бібліотеку `Numpy`

In [ ]:
%pip install numpy

### Починаємо роботу з `Numpy`
> імпортуємо бібліотеку

In [ ]:
import numpy as np

> вчимось основам використання масивів та їх порівняння з простими Python List

In [ ]:
import sys
l = [1, 2, 3, 6, 7, 8, 9, 12, 14, 16]
print(f"Маємо масив {type(l)} довжиною {len(l)} який займає в памяті {sys.getsizeof(l)} байти")
a = np.array(l)
print(f"Маємо Numpy масив {type(a)} довжиною {len(a)} який займає в памяті {sys.getsizeof(a)} байти")

print("Переконаємось, що для великих розмірів Numpy краще використовують память компютера:")
l2 = list(range(100, 10000))
a2 = np.array(l2)
print(f"{type(l2)} займає в памяті {sys.getsizeof(l2)} байти,\n{type(a2)} займає в памяті {sys.getsizeof(a2)} байти")

> Вчимось виконувати операції над масивами

In [ ]:
items = [int(5), float(5), list([5]), np.array([5])]
print(f"Маємо {type(items)} з наборів різних даних:")
for item in items:
    print(f"Маємо число {item} типу {type(item)}")

print("Покажемо як виконувати арифметичні операції")

a = items[0] + items[1]
print(f"Результат: {a} типу {type(a)}")
a = items[0] + items[2][0]
print(f"Результат: {a} типу {type(a)}")
a = items[0] + items[-1]
print(f"Результат: {a} типу {type(a)}. Зверніть увагу, що нам не потрібно розкривати масив.")

print("Покажемо кращий приклад з масивами де ми хочемо виконати (х * 5 + 6) над кожним елементом масиву:")

l = [1, 2, 3]
n = np.array(l)

a = [i * 5 + 6 for i in l]
print(f"Результат: {a} типу {type(a)}")
a = n * 5 + 6
print(f"Результат: {a} типу {type(a)}")


### Виконаємо приклад з документації Nampy
[Розв'яжемо приклад за формулою](https://numpy.org/doc/stable/user/absolute_beginners.html#working-with-mathematical-formulas)
![formula](./formula.png)

In [ ]:
from numpy.random import randint, random

n = 2
Y_prediction = np.array([2, 4]) #randint(1, 100, size=n) # Це є цілі числа
Y = np.array([0.2, 0.6]) #random(size=n) # Це є числа з плаваючою крапкою від 0 до 1

MSE = np.sum(np.square(Y_prediction - Y)) / n # Це наша формула

print(f"Якщо Y_prediction = {Y_prediction} та Y = {Y} то за формулою будемо мати: {MSE}")

print("А ось так воно виглядає чистим пайтоном:")

Y_prediction = [2, 4]
Y = [0.2, 0.6]

MSE = []
for i in range(n):
    MSE.append((Y_prediction[i] - Y[i])**2)

MSE_final = sum(MSE)/n
print(f"Якщо Y_prediction = {Y_prediction} та Y = {Y} то за формулою будемо мати: {MSE} та результат {MSE_final}")

### Методи створення масивів в Numpy
> `range` VS `np.arrange` - згенерувати послідовність чисел з певним кроком в діапазоні від Start-Stop

In [ ]:
l = list(range(15))
print(f"Згенерували {type(l)} на {len(l)} елементів, де 0-й елемент {l[0]} та останній елемент {l[-1]}")
# Звісно можна просто перетворити попередній List в масив Numpy
a = np.array(l)
print(f"Згенерували {type(a)} на {len(a)} елементів, де 0-й елемент {a[0]} та останній елемент {a[-1]}")
# Однак краще використовувати методи Numpy
n = np.arange(15)
print(f"Згенерували {type(n)} на {len(n)} елементів, де 0-й елемент {n[0]} та останній елемент {n[-1]}")
n2 = np.arange(10, 15, 2)
print(f"Оскільки останній елемент не враховується то будемо мати тільки {len(n2)} які є: {n2}")
n3 = np.arange(10, 14, 2)
print(f"Оскільки останній елемент не враховується то будемо мати тільки {len(n3)} які є: {n3}")
n4 = np.arange(10, 12, step=.2)
print(f"Якщо крок дробовий то буде {len(n4)} де 0-й елемент {n4[0]} та останній елемент {n4[-1]} та можемо його округлити до 2-х знаків {np.round(n4[-1], 2)}")


`np.linspace` - генерує масив, якщо нам потрібна задана кількість елементів на проміжку

In [ ]:
n = np.linspace(10, 12, num=20)
print(f"Згенерували {type(n)} на {len(n)} елементів, де 0-й елемент {n[0]} та останній елемент {n[-1]}")
print(f"Подивимось на всі елементи масиву:\n {n}")
print(f"Спробуємо округлити до 2-х знаків після коми:\n {np.around(n, 2)}")

### Візуальний приклад

In [ ]:
%pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
N = 20
x = np.linspace(10, 12, num=N)
y = np.linspace(20, 30, num=N)
plt.plot(x, y, 'o', label="linspace")

x1 = np.arange(10, 12, step=.1)
y1 = np.arange(20, 30, step=.5)

plt.plot(x1, y1, 'o', label="arange")
print(f"Але ми мали однакову кількість елементів {len(x)} = {len(x1)}, Перший елемент рівний {x[0]} = {x1[0]}. Останні елементи не рівні {x[-1]} =/ {x1[-1]}")

plt.legend()
plt.show()

### Можна зберегти попередній графік та просто вивести його за допомогою Markdown
![Збережений графік](./fig_1.png)

### Розуміння векторів та матриць
> Вектор рядок та вектор стовпець

In [ ]:
vr = np.arange(16)
print(f"Це буде вектор рядок:\n {vr}")
vs = np.arange(16).reshape(16, 1)
print(f"Це вектор стовпець:\n {vs}")

In [ ]:
vr1 = np.array([1, 2, 3])
vr2 = np.array([4, 5, 6])
vs1 = np.array([[1], [2], [3]])
vs2 = np.array([[4], [5], [6]])
print(f"""
Вектор ряди які створили вручну будуть виглядати:
VR1=
{vr1}
---
VR2=
{vr2}
Вектор стовпці які створили вручну будуть виглядати:
VS1=
{vs1}
---
VS2=
{vs2}
""")

print("Спробуємо додавання однакових векторів:")
print(f"""
VR1+VR2=
{vr1+vr2}
---
VS1+VS2=
{vs1+vs2}
---
При додаванні різних типів векторів будемо мати матрицю:
VR1+VS1=
{vr1+vs1}
""")

> Визначення форми (shape) вектора та її зміна (reshape)

In [ ]:
print(f"""Вектор рядок має форму {vr.shape} та к-сть вимірів {vr.ndim} 
A вектор стовпець має форму {vs.shape} та к-сть вимірів {vs.ndim}""")
for vm in (vs.reshape(4, 2, 2), vs.reshape(4, 4, 1), vs.reshape(2, 2, 2, 2), vr.reshape(1, 1, 2, 2, 4)):
    print(f"Можна зробити {vm.ndim}-х вимірний масив/матрицю: з формою {vm.shape}:\n{vm}")


print("Добуток всіх значень форми по кожній з осей має бути рівним = загальній к-сть елементів масиву")

In [ ]:
from matplotlib import image
from matplotlib import pyplot

image = image.imread('formula.png')

print(f"Ми прочитали зображення яке буде мати тип: {image.dtype}")
print(f"Зображення представлене матрицею буде мати форму: {image.shape}")

np_image = np.array(image)
cut_np_image = np_image[110:400, 170:2100]


pyplot.imshow(np_image[110:400, 170:2100]*0.7)
pyplot.show()

### Робота з векторами та матрицями
> `slicing` - дає можливість витягнути підматрицю з основної матриці

In [19]:
m = np.arange(40).reshape(4, 10)
print(f"Згенерували матрицю з {m.ndim}-х вимірів та формою {m.shape}:\n{m}")

Згенерували матрицю з 2-х вимірів та формою (4, 10):
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [31]:
print(f"""
Матриця {n.ndim}-x вимірна, тому коли беремо один індекс, то витягуємо вектор:
Беремо весь рядок:
{m[0]}
Беремо весь стовпець (який перетвориться в рядок):
{m[:, 0]}
Якщо хочемо взяти лише певний елемент (наприклад число 11, 25) тоді:
{m[1, 1]} | {m[2, 5]}
Якщо хочемо взяти діапазон чисел:
{m[:, 2::3]}
Також можна використовувати від'ємні індекси:
{m[-1, -1]}
Від'ємні індекси для діапазону:
{m[:, -4:]}
""")


Матриця 1-x вимірна, тому коли беремо один індекс, то витягуємо вектор:
Беремо весь рядок:
[0 1 2 3 4 5 6 7 8 9]
Беремо весь стовпець (який перетвориться в рядок):
[ 0 10 20 30]
Якщо хочемо взяти лише певний елемент (наприклад число 11, 25) тоді:
11 | 25
Якщо хочемо взяти діапазон чисел:
[[ 2  5  8]
 [12 15 18]
 [22 25 28]
 [32 35 38]]
Також можна використовувати від'ємні індекси:
39
Від'ємні індекси для діапазону:
[[ 6  7  8  9]
 [16 17 18 19]
 [26 27 28 29]
 [36 37 38 39]]



In [37]:
e = np.empty(10, dtype=int)
print(f"Наприклад можемо ініціалізувати пустий масив з елементами int який буде мати довільні дані, залежно від зберігання в памяті:\n{e}")

i = np.ones(10)
print(f"масив з одиницями: \n{i}")

Наприклад можемо ініціалізувати пустий масив з елементами int який буде мати довільні дані, залежно від зберігання в памяті:
[         0 1072693248          0 1073741824          0 1074003968
          0 1075052544          0 1076101120]
масив з одиницями: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
