In [5]:
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature *5
print(f"При множенні на 5 маємо: {t1}")
print("""
Чому маємо такий результат?
---
Тому, що ми беремо цілий масив і множимо на число, тому він виводиться 5 разів(тобто число на яке множимо)
""")
t1 = [x*5 for x in temperature]
print(f"Тепер отримаємо: {t1}")
print("""
Чому тепер множення успішне?
---
Тому, що тепер ми беремо кожен окремий елемент масиву і множимо на число 5
""")
t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)
t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

Чому маємо такий результат?
---
Тому, що ми беремо цілий масив і множимо на число, тому він виводиться 5 разів(тобто число на яке множимо)

Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

Чому тепер множення успішне?
---
Тому, що тепер ми беремо кожен окремий елемент масиву і множимо на число 5

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]


### Вектори, створення та робота з ними

In [7]:
print("""
Все можна створити в ручну за допомогою методу np.array
передавши йому набір значень у вигляді List:
""")
vector_row = np.array([1, -5, 3, 2, 4])
vector_column = np.array([[1],
                         [2],
                         [3],
                         [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)


Все можна створити в ручну за допомогою методу np.array
передавши йому набір значень у вигляді List:

[ 1 -5  3  2  4] 
Вектор має розмір (5,)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


### Метод `arange` - генерує послідовність чисел з певним кроком у заданому інтервалі

In [17]:
start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {x[0:5]} та методом arange: {a[0:5]}")
print("Виведіть весь діапазон чисел.")
print(f"Виводимо весь діапазон числе починаючи з 0, з кроком 5:\n{a[0:100:5]}")



Масив згенерований простим range: range(0, 5) та методом arange: [0 1 2 3 4]
Виведіть весь діапазон чисел.
Виводимо весь діапазон числе починаючи з 0, з кроком 5:
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
