In [2]:
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature *5
print(f"При множенні на 5 маємо: {t1}")
print("""
Чому маємо такий результат?
---
Тому, що ми беремо цілий масив і множимо на число, тому він виводиться 5 разів(тобто число на яке множимо)
""")
t1 = [x*5 for x in temperature]
print(f"Тепер отримаємо: {t1}")
print("""
Чому тепер множення успішне?
---
Тому, що тепер ми беремо кожен окремий елемент масиву і множимо на число 5
""")
t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)
t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

Чому маємо такий результат?
---
Тому, що ми беремо цілий масив і множимо на число, тому він виводиться 5 разів(тобто число на яке множимо)

Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

Чому тепер множення успішне?
---
Тому, що тепер ми беремо кожен окремий елемент масиву і множимо на число 5

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]


### Вектори, створення та робота з ними

In [3]:
print("""
Все можна створити в ручну за допомогою методу np.array
передавши йому набір значень у вигляді List:
""")
vector_row = np.array([1, -5, 3, 2, 4])
vector_column = np.array([[1],
                         [2],
                         [3],
                         [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)


Все можна створити в ручну за допомогою методу np.array
передавши йому набір значень у вигляді List:

[ 1 -5  3  2  4] 
Вектор має розмір (5,)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


### Метод `arange` - генерує послідовність чисел з певним кроком у заданому інтервалі

In [10]:
start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {x[0:5]} та методом arange: {a[0:5]}")
print("Виведіть весь діапазон чисел.")
print(f"Виводимо весь діапазон числе починаючи з 0, з кроком 5:\n{a[0:100:5]}")

a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
print("Виведіть останній діапазон в згенерованому масиві.")
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[-1]}")

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", list(x)[0], )
print("Виведіть якесь число з середини діапазону.")
print("Якесь число з середини діапазону:", list(x)[25], )

# дробові числа
x = np.arange(10.4)
print("Будем мати:", x)
# крок
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)
# Заокруглення
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\n Зерніть уагу на заокруглення")
print("Згенеруйте значення де крок буде мати чотири нулі після коми, яким буде результат?")
x = np.arange(0.5, 4, 0.001)
print("З кроком 4 нулі після коми:", x,)
y = x * 2.5
print("Після перемноження:", y)
print("Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат?")
y = (x * x) / 0.4
print("Результат:", y)



Масив згенерований простим range: range(0, 5) та методом arange: [0 1 2 3 4]
Виведіть весь діапазон чисел.
Виводимо весь діапазон числе починаючи з 0, з кроком 5:
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
Можемо задавати початок генерації вектора, перший елемент: 5
Виведіть останній діапазон в згенерованому масиві.
Можемо задавати початок генерації вектора, перший елемент: 99
Те саме але з вбудованою функцією range: range(5, 100)
Власне вивід значень: 5
Виведіть якесь число з середини діапазону.
Якесь число з середини діапазону: 30
Будем мати: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
З кроком 0.5: [0.5 1.  1.5 2.  2.5 3.  3.5]
З кроком 0.08: [0.04 0.12 0.2  0.28 0.36 0.44 0.52 0.6  0.68 0.76 0.84 0.92 1.   1.08
 1.16 1.24 1.32 1.4  1.48 1.56 1.64 1.72 1.8 ] 
 Зерніть уагу на заокруглення
Згенеруйте значення де крок буде мати чотири нулі після коми, яким буде результат?
З кроком 4 нулі після коми: [0.5   0.501 0.502 ... 3.997 3.998 3.999]
Після перемноження: [1.

### Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням

In [13]:
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")
#print(f"Власне числа: {a}")
print("Виведіть кожне друге число згенерованого діапазону. Тут будее потрібен цикл :)")
for i in range(1, len(a), 2):
    print(a[i])

print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
print("Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")
a = np.linspace(start, size_of_vec, 100)
print("Перші 10 чисел:")
for i in range(10):
    print(a[i])

print("Останні 10 чисел:")
for i in range(-10, 0):
    print(a[i])

print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")

print(np.linspace(start, size_of_vec, 5, endpoint=False))
print("Спробуйте самі порахуавти крок.")

_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")
print("Чому маємо такий крок?")
print(f"""
Якщо параметр endpoint=True, то останнє число у діапазоні включається, 
тому кількість інтервалів, що треба пройти, дорівнює кількості чисел - 1.
Якщо параметр endpoint=False, то останнє число у діапазоні не включається, 
тому кількість інтервалів, що треба пройти, дорівнює кількості чисел. 
""")

Згенерували 50 чисел в діапазоні 5.0 до 100.0
Виведіть кожне друге число згенерованого діапазону. Тут будее потрібен цикл :)
6.938775510204081
10.816326530612244
14.693877551020408
18.57142857142857
22.448979591836736
26.3265306122449
30.20408163265306
34.08163265306122
37.95918367346939
41.83673469387755
45.714285714285715
49.59183673469388
53.46938775510204
57.3469387755102
61.224489795918366
65.10204081632654
68.9795918367347
72.85714285714286
76.73469387755102
80.61224489795919
84.48979591836735
88.36734693877551
92.24489795918367
96.12244897959184
100.0
Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]
Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.
Перші 10 чисел:
5.0
5.959595959595959
6.919191919191919
7.878787878787879
8.838383838383837
9.797979797979798
10.757575757575758
11.717171717171716
12.676767676767676
13.636363636363637
Останні 10 чисел:
91.36363636363636
92.32323232323232
93.28282828282828
94.24242424242424
95.2020202020202
96

### Типи масивів/векторів

In [ ]:
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2],[3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]] ])
    }
for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-"*10)

homework("""Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension).
Чому значення для векторів та матриць однакове та не співпдає з значенням shape?
Задайте власні вектори з різними числами.""")